name: flutter_dev_test
description: "Developer's Flutter test"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  otp: ^3.1.4
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.16
  flutter_bloc: ^8.1.6
  dartz: ^0.10.1
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  convert: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/svg/
    - assets/svg/icons/
    - assets/svg/system/
  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-Light.ttf
          weight: 300
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/PlusJakartaSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/PlusJakartaSans-Italic.ttf
          style: italic
        - asset: assets/fonts/PlusJakartaSans-BoldItalic.ttf
          weight: 700
          style: italic

